/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Variant({
  'starters' : IDL.Null,
  'chinese' : IDL.Null,
  'biryani' : IDL.Null,
  'drinks' : IDL.Null,
});
export const FoodType = IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null });
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Float64,
  'isSpecial' : IDL.Bool,
  'foodType' : FoodType,
});
export const SpecialDish = IDL.Record({
  'tag' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getMenuByType' : IDL.Func([FoodType], [IDL.Vec(MenuItem)], ['query']),
  'getSpecialDishes' : IDL.Func([], [IDL.Vec(SpecialDish)], ['query']),
  'getSpecialMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Variant({
    'starters' : IDL.Null,
    'chinese' : IDL.Null,
    'biryani' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const FoodType = IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Float64,
    'isSpecial' : IDL.Bool,
    'foodType' : FoodType,
  });
  const SpecialDish = IDL.Record({
    'tag' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getMenuByType' : IDL.Func([FoodType], [IDL.Vec(MenuItem)], ['query']),
    'getSpecialDishes' : IDL.Func([], [IDL.Vec(SpecialDish)], ['query']),
    'getSpecialMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };