/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FoodType = { 'veg' : null } |
  { 'nonVeg' : null };
export type MenuCategory = { 'starters' : null } |
  { 'chinese' : null } |
  { 'biryani' : null } |
  { 'drinks' : null };
export interface MenuItem {
  'name' : string,
  'description' : string,
  'category' : MenuCategory,
  'price' : number,
  'isSpecial' : boolean,
  'foodType' : FoodType,
}
export interface SpecialDish {
  'tag' : string,
  'name' : string,
  'description' : string,
}
export interface Testimonial {
  'customerName' : string,
  'review' : string,
  'rating' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getMenuByType' : ActorMethod<[FoodType], Array<MenuItem>>,
  'getSpecialDishes' : ActorMethod<[], Array<SpecialDish>>,
  'getSpecialMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];